name: 'Deploy App to Cloud Run'

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - 'terraform/**'
      - 'README.md'

env:
  PROJECT_ID: "flovery-489720"
  REGION: "europe-west4"
  REPO_NAME: "bloom-repo"
  SERVICE_NAME: "bloom-catalog-api"

# ДОДАЄМО ПРАВА ДЛЯ WIF
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ЗМІНЕНО: Авторизація через Workload Identity Federation
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/138796438230/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'github-actions-sa@flovery-489720.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Deploy to Cloud Run
      run: |
        IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE_TAG \
          --region ${{ env.REGION }} \
          --quiet